"""Initial migration.

Revision ID: 1531db377c74
Revises: 
Create Date: 2022-01-27 22:49:53.706957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1531db377c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('company', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_vacancies_status'), 'temp_vacancies', ['status'], unique=False)
    op.create_foreign_key(None, 'favorites', 'users', ['id_user'], ['id'])
    op.create_foreign_key(None, 'favorites', 'vacancies', ['id_vacancy'], ['id'])
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_roles_privilege'), 'roles', ['privilege'], unique=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'phonenumber',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.add_column('vacancies', sa.Column('source', sa.String(length=80), nullable=False))
    op.alter_column('vacancies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('vacancies', 'source')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phonenumber',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_roles_privilege'), table_name='roles')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_index(op.f('ix_temp_vacancies_status'), table_name='temp_vacancies')
    op.drop_table('temp_vacancies')
    # ### end Alembic commands ###
