"""empty message

Revision ID: d34fddd248fc
Revises: 
Create Date: 2022-02-12 21:14:39.375853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34fddd248fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Favorite', 'User', ['id_user'], ['id'])
    op.create_foreign_key(None, 'Favorite', 'Job', ['id_vacancy'], ['id'])
    op.alter_column('Job', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Job', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Job', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Job', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Job', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Job', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Job', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Role', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_Role_privilege'), 'Role', ['privilege'], unique=False)
    op.alter_column('TempJob', 'state',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_index('ix_temp_vacancies_status', table_name='TempJob')
    op.create_index(op.f('ix_TempJob_status'), 'TempJob', ['status'], unique=False)
    op.alter_column('User', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('User', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'phonenumber',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'User', 'Role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.alter_column('User', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'phonenumber',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_TempJob_status'), table_name='TempJob')
    op.create_index('ix_temp_vacancies_status', 'TempJob', ['status'], unique=False)
    op.alter_column('TempJob', 'state',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_index(op.f('ix_Role_privilege'), table_name='Role')
    op.alter_column('Role', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Job', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Job', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Job', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Job', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Job', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Job', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Job', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'Favorite', type_='foreignkey')
    op.drop_constraint(None, 'Favorite', type_='foreignkey')
    # ### end Alembic commands ###
