"""empty message

Revision ID: ddd9bb76cd30
Revises: 
Create Date: 2022-01-10 23:41:14.735557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd9bb76cd30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorites', 'users', ['id_user'], ['id'])
    op.create_foreign_key(None, 'favorites', 'vacancies', ['id_vacancy'], ['id'])
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_roles_privilege'), 'roles', ['privilege'], unique=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'phonenumber',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.alter_column('vacancies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phonenumber',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_roles_privilege'), table_name='roles')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    # ### end Alembic commands ###
